'------------------------------------------------------------------------------
' <auto-generated>
'     This file was generated by a tool.
'     Runtime compilation can generate this automatically in Visual Studio.
'-------------------------------------------------------------------------------

Imports System
Imports System.Diagnostics

Partial Public Class AttendanceDetails
    Inherits System.Web.UI.Page
End Class

