'------------------------------------------------------------------------------
' <auto-generated>
'     This file was generated by a tool.
'     Runtime compilation can generate this automatically in Visual Studio.
'-------------------------------------------------------------------------------

Partial Public Class CanteenMaster
    Inherits System.Web.UI.Page
End Class

